version: "3.10"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "${PASSWORD}"
      POSTGRES_USER: "${USER}"
      POSTGRES_DB: "${DB}"
    
    ports:
      - "${DB_PORT}:${DB_PORT}"
  web:
    build: .
    environment:
      DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME}"
      DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - .:/app
    depends_on:
      - db