version: "3.10"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    # env_file:
    #   - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data: