version: "3.10"
services:
  db:
    image: postgres:latest
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mnk3mnk3
      POSTGRES_USER: bahy
      POSTGRES_DB: db1
    ports:
      - "5432:5432"
    command: chmod 0700 ./var/lib/postgresql/data
  web:
    build: .
    environment:
      POSTGRES_PASSWORD: mnk3mnk3
      POSTGRES_USER: bahy
      POSTGRES_DB: db1
    ports:
      - 8000:8000
    volumes:
      - ./playground:/app/playground
    depends_on:
      - db
# volumes:
#   data:
#     driver: local


# version: "3.9"
   
# services:
#   db:
#     image: postgres
#     volumes:
#       - ./data/db:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./vyshdjangoproject:/code
#     ports:
#       - "8000:8000"
#     environment:
#       - POSTGRES_NAME=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     depends_on:
#       - db