# Generated by Django 4.2.3 on 2023-07-23 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_course_id_alter_person_id_alter_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='registration_date',
        ),
    ]
