# Generated by Django 4.2.3 on 2023-07-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("Age", models.IntegerField()),
                ("Address", models.CharField(max_length=100)),
                ("Phone", models.CharField(max_length=20)),
            ],
        ),
    ]
