# Generated by Django 4.2.3 on 2023-07-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_course_rename_address_student_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
