on:
  push:
    branches: [ main ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run flake8
        uses: github/codeql-action/init@v2
      - name: Format imports
        uses: psf/black@stable
#         with:
#           args: .
